<a href="https://colab.research.google.com/github/MLcmore2023/MLcmore2023/blob/main/day3_pm_afternoon/random-forest-demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Numpy syntaxes

`random.choice` is for generating random sample

In [91]:
import numpy as np
np.random.choice(1000, 3)

array([252, 307, 881])

There is an optional parameter of `replace`, that determines whether the sample is with or without replacement. Default is True, meaning that a value of a can be selected multiple times.



In [92]:
np.random.choice(10, 5, replace=True) # the numbers can repeat

array([3, 0, 8, 8, 0])

In [93]:
np.random.choice(10, 5, replace=False) # the numbers cannot repeat

array([7, 5, 2, 9, 4])

_Question:_ what will this do?
`np.random.choice(100, 100, replace=False) # the numbers cannot repeat`
<details>
<summary>Click for answer</summary>
It generate a sequence of 100 unique numbers chosen randomly from the range 0 to 99. Each number is chosen only once. In other words, this code generates a random permutation of the numbers from 0 to 99, ensuring that each number appears exactly once in the resulting sequence. This is often used in situations where you need to shuffle or randomize a set of unique items.
</details>


In [110]:
np.random.choice(100, 100, replace=False) # the numbers cannot repeat

array([15, 22, 74, 27, 90, 47, 81,  5, 54, 25, 60, 92, 38, 14, 39,  1, 16,
       89, 93, 53, 13, 41, 59, 91,  8, 97, 10, 67, 37, 55, 69, 79, 57, 50,
       58, 72, 83, 18, 45, 70, 61, 26, 30,  3, 29, 17, 12, 99, 48, 31, 77,
       82,  0, 19, 42, 71, 64, 36, 87,  6, 65, 63, 94, 84, 46, 24, 35, 11,
       23, 96, 76, 73, 98, 32, 75, 80, 33, 21, 68, 86, 34, 28,  4, 44, 78,
       62, 51, 20, 66, 52, 85, 56, 40, 49, 43,  9, 95, 88,  2,  7])

_Question:_ what will this do?
`np.random.choice(100, 100, replace=True)`
<details>
<summary>Click for answer</summary>
this code generates a sequence of 100 numbers where each number is independently drawn from the range 0 to 99, and repetition is allowed. This type of sampling can result in duplicate numbers in the output sequence.
</details>


In [111]:
np.random.choice(100, 100, replace=True) # the numbers can repeat

array([50, 66, 56, 80, 78, 57, 12, 40, 57, 82, 19, 66, 68, 87, 22, 41, 60,
       12, 65, 18, 82,  3, 63, 21, 39,  8, 65, 41, 32, 54, 48, 18, 31, 98,
       51, 60, 98, 15, 20, 17, 39, 66, 77, 62, 12, 47, 34, 93, 19, 48,  9,
       27, 69, 37, 87, 62, 24, 57, 10, 74,  8,  3, 80, 28, 53, 38, 25, 36,
        8, 56, 94, 10, 36, 85, 39, 28, 49, 99, 33, 43, 91, 28, 65, 94, 46,
       30, 78, 65, 32, 10, 90, 13, 10, 60, 61, 21, 48, 87, 76, 35])

Since we allow repeated items, the list will not contain all numbers between 0 to 99. We and use the following code to check how many numbers are NOT in the sample. We will find out that about 36% of numbers are not in the list.

In [135]:
numbers = np.random.choice(1000, 1000, replace=True)
count_of_missing_numbers = 0
for i in range(1000):
  if i not in numbers:
    count_of_missing_numbers+=1

print(count_of_missing_numbers/1000)

0.351


_Review Question:_
<details>
<summary>Click for answer</summary>
`array[indices]`
</details>


In [109]:
array = np.array(['a','b','c','d','e','f','g','h'])
indices = np.array([0,2,3,6])

# how do I get the item 0,2,3,6 from array?
new_array = None ### code here
print(new_array)

None


# Random Forest
Random forest is an ensemble machine learning algorithm that combines multiple decision trees to make accurate classification and regression. It works by training numerous decision trees on different subsets of the dataset using bootstrapping (random sampling with replacement) and feature randomization. These trees collectively form a "forest," and their predictions are averaged. Random forests are also non-parametric and require little to no parameter tuning. They differ from many common machine learning models used today that are typically optimized using gradient descent.

<img src="https://www.tibco.com/sites/tibco/files/media_entity/2021-05/random-forest-diagram.svg">


### Import libraries and initialize random generator

In [94]:
import numpy as np
from sklearn.datasets import fetch_openml # for loadin dataset
# Set the seed value to make the random number reproducible
np.random.seed(0)

### Load data using `sklearn` library
The sonar dataset contains data collected from sonar signals that were used to discriminate between underwater objects as either "rocks" or "mines." The dataset consists of 208 observations, each represented by 60 features from sonar signals. The signals are obtained from a variety of different aspect angles. The goal is to classify these signals and distinguish between `rocks` and `mines`.

<img src="https://storage.googleapis.com/kaggle-datasets-images/1662635/2727659/3493b9309a1cf4f0c07aa6175b820060/dataset-card.jpg?t=2021-11-13-14-25-59" width=20%>

In [95]:
# Load the Sonar dataset from scikit-learn's datasets
sonar_data = fetch_openml(name='sonar', version=1, as_frame=True)

# The dataset is loaded as a dictionary-like object
X = sonar_data['data']    # Feature matrix
y = sonar_data['target']  # Target values

/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [96]:
X

attribute_1  attribute_2  attribute_3  attribute_4  attribute_5  \
0         0.0200       0.0371       0.0428       0.0207       0.0954   
1         0.0453       0.0523       0.0843       0.0689       0.1183   
2         0.0262       0.0582       0.1099       0.1083       0.0974   
3         0.0100       0.0171       0.0623       0.0205       0.0205   
4         0.0762       0.0666       0.0481       0.0394       0.0590   
..           ...          ...          ...          ...          ...   
203       0.0187       0.0346       0.0168       0.0177       0.0393   
204       0.0323       0.0101       0.0298       0.0564       0.0760   
205       0.0522       0.0437       0.0180       0.0292       0.0351   
206       0.0303       0.0353       0.0490       0.0608       0.0167   
207       0.0260       0.0363       0.0136       0.0272       0.0214   

     attribute_6  attribute_7  attribute_8  attribute_9  attribute_10  ...  \
0         0.0986       0.1539       0.1601       0.3109        0.2111  ...   
1         0.2583       0.2156       0.3481       0.3337        0.2872  ...   
2         0.2280       0.2431       0.3771       0.5598        0.6194  ...   
3         0.0368       0.1098       0.1276       0.0598        0.1264  ...   
4         0.0649       0.1209       0.2467       0.3564        0.4459  ...   
..           ...          ...          ...          ...           ...  ...   
203       0.1630       0.2028       0.1694       0.2328        0.2684  ...   
204       0.0958       0.0990       0.1018       0.1030        0.2154  ...   
205       0.1171       0.1257       0.1178       0.1258        0.2529  ...   
206       0.1354       0.1465       0.1123       0.1945        0.2354  ...   
207       0.0338       0.0655       0.1400       0.1843        0.2354  ...   

     attribute_51  attribute_52  attribute_53  attribute_54  attribute_55  \
0          0.0232        0.0027        0.0065        0.0159        0.0072   
1          0.0125        0.0084        0.0089        0.0048        0.0094   
2          0.0033        0.0232        0.0166        0.0095        0.0180   
3          0.0241        0.0121        0.0036        0.0150        0.0085   
4          0.0156        0.0031        0.0054        0.0105        0.0110   
..            ...           ...           ...           ...           ...   
203        0.0203        0.0116        0.0098        0.0199        0.0033   
204        0.0051        0.0061        0.0093        0.0135        0.0063   
205        0.0155        0.0160        0.0029        0.0051        0.0062   
206        0.0042        0.0086        0.0046        0.0126        0.0036   
207        0.0181        0.0146        0.0129        0.0047        0.0039   

     attribute_56  attribute_57  attribute_58  attribute_59  attribute_60  
0          0.0167        0.0180        0.0084        0.0090        0.0032  
1          0.0191        0.0140        0.0049        0.0052        0.0044  
2          0.0244        0.0316        0.0164        0.0095        0.0078  
3          0.0073        0.0050        0.0044        0.0040        0.0117  
4          0.0015        0.0072        0.0048        0.0107        0.0094  
..            ...           ...           ...           ...           ...  
203        0.0101        0.0065        0.0115        0.0193        0.0157  
204        0.0063        0.0034        0.0032        0.0062        0.0067  
205        0.0089        0.0140        0.0138        0.0077        0.0031  
206        0.0035        0.0034        0.0079        0.0036        0.0048  
207        0.0061        0.0040        0.0036        0.0061        0.0115  

[208 rows x 60 columns]

In [97]:
y

0      Rock
1      Rock
2      Rock
3      Rock
4      Rock
       ... 
203    Mine
204    Mine
205    Mine
206    Mine
207    Mine
Name: Class, Length: 208, dtype: category
Categories (2, object): ['Mine', 'Rock']

There are two classes in our dataset: Rock and Mine. The labels are in strings, so we will convert these categorical labels from strings (e.g., "Rock" and "Mine") into 0 and 1. By converting strings to numbers, the models can process the data more efficiently.

In [98]:
mapping = {"Rock": 0, "Mine": 1}

# Use the map function to apply the mapping and convert strings to integers
y = y.map(mapping)
y

0      0
1      0
2      0
3      0
4      0
      ..
203    1
204    1
205    1
206    1
207    1
Name: Class, Length: 208, dtype: category
Categories (2, int64): [1, 0]

we now convert the dataset into numpy arrays so later we can perform calculations on them

In [99]:
X = X.to_numpy()
y = y.to_numpy()

### Split the dataset into training sets and testing sets

In [100]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# REVIEW: decision trees

In [101]:
from sklearn.tree import DecisionTreeClassifier

# Create and train the Decision Tree model
decision_tree = DecisionTreeClassifier(max_depth=None)
decision_tree.fit(X_train, y_train)

# Make predictions on the test set
predictions = decision_tree.predict(X_test)

# See result
print(y_test)
print(predictions)

[0 0 0 0 1 0 1 1 0 1 0 1 0 1 0 0 1 0 0 0 1 0 0 0 0 1 1 1 1 1 0 1 1 0 1 1 1
 1 0 1 1 0]
[1 1 1 0 1 1 1 1 1 0 0 1 0 1 0 0 1 0 0 0 0 1 1 1 0 1 0 1 1 1 0 0 1 0 1 1 1
 1 1 1 1 0]


In [102]:
print(y_test==predictions)

[False False False  True  True False  True  True False False  True  True
  True  True  True  True  True  True  True  True False False False False
  True  True False  True  True  True  True False  True  True  True  True
  True  True False  True  True  True]


In [103]:
N = len(y_test)
count_of_correct_predictions = sum( y_test==predictions  )
accuracy = count_of_correct_predictions/N
print(accuracy)

0.6904761904761905


### Initialize model
In random forest, the model is simply a list of individual decision trees.
` [🌳0, 🌳1, 🌳2, 🌳3... ]`

Therefore, to initialize the model, we just make an empty list

In [104]:
random_forest_model = [] # empty list

### Bootstrapping
One of the main reasons random forests are a powerul machine learning model is the idea behind injecting randomness into each tree. Each individual decision tree will be constructed on a "bootstrapped" subset of our data. If our dataset has $n$ observations "bootstrapping" is the process of sampling $n$ points **with** replacement. We can actually calculate that the probability an observation is omitted from our bootstrapped dataset is  $(1 - \frac{1}{n})^{n}$. By definition $e^{-1} = \displaystyle \lim_{n\to\infty}(1-\frac{1}{n})^n$ and since $e^{-1}$ = 0.36787.. $\approx \frac{1}{3}$ $\Rightarrow$ bootstrapping $n$ samples with replacement will leave out approximately $\frac{1}{3}$ of the observations in each distinct tree. Since each individual tree is built using only $\frac{2}{3}$ of the data we'll  find that most trees will differ from one another

In [139]:
example_list = np.array(['a','b','c','d','e','f','g','h'])
N = 8

In [153]:
bootstrap_indices = np.random.choice(N, N, replace=True)
bootstrap_indices.sort() # sort the array so it is easier for us to read (this is not necessary)
print(bootstrap_indices)

[0 0 1 3 3 4 6 6]


In [154]:
bootstrap_sample = example_list[bootstrap_indices]
print(bootstrap_sample)

['a' 'a' 'b' 'd' 'd' 'e' 'g' 'g']


In [155]:
def bootstrap_sampling(X, y):
    N = X.shape[0] # how many entries are there in the dataset
    bootstrap_indices = np.random.choice(N, N, replace=True)

    X_bootstrap = X[bootstrap_indices]
    y_bootstrap = y[bootstrap_indices]

    return X_bootstrap, y_bootstrap

In [158]:
n_estimators = 100 # The number of trees in the forest
max_depth = 50
max_features = 100

def train_random_forest(X, y, random_forest_model):
    n_samples, n_features = X.shape

    for i in range(n_estimators):
        # Bootstrap sampling
        X_bootstrap, y_bootstrap = bootstrap_sampling(X,y)

        # Create a Decision Tree and fit it to the bootstrap sample
        tree = DecisionTreeClassifier(max_depth=max_depth, max_features=max_features)
        tree.fit(X_bootstrap, y_bootstrap)

        # Append the trained Decision Tree to the list of estimators
        random_forest_model.append(tree)

def predict(X, random_forest_model):
    predictions = np.array([tree.predict(X) for tree in random_forest_model])
    # Take majority vote for each sample
    return np.apply_along_axis(lambda x: np.bincount(x).argmax(), axis=0, arr=predictions)

# Create and train the Random Forest model
train_random_forest(X_train, y_train, random_forest_model)

# Make predictions on the test set
predictions = predict(X_test, random_forest_model)

In [159]:
print(y_test==predictions)

N = len(y_test)
count_of_correct_predictions = sum( y_test==predictions  )
accuracy = count_of_correct_predictions/N
print(accuracy)

[ True False False  True  True  True  True  True  True False False  True
  True  True  True  True  True  True  True  True  True  True False  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True False  True  True  True]
0.8571428571428571


## References
- L. Breiman. Random forests. Maching Learning, 45(1):5–32, Oct. 2001. [[pdf]](https://link.springer.com/content/pdf/10.1023%2FA%3A1010933404324.pdf)
- https://carbonati.github.io/posts/random-forests-from-scratch/
- https://www.tibco.com/reference-center/what-is-a-random-forest