<a href="https://colab.research.google.com/github/MLcmore2023/MLcmore2023/blob/main/question.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Question 3 code

Your task is to complete the code to predict the weight of someone using a height and gender.

In [22]:
import pandas as pd
import numpy as np
# weight-height dataset
dataset = pd.read_csv("https://gist.githubusercontent.com/nstokoe/7d4717e96c21b8ad04ec91f361b000cb/raw/bf95a2e30fceb9f2ae990eac8379fc7d844a0196/weight-height.csv")
gender_mapping = {'Male': 0, 'Female': 1}
dataset["Gender"] = dataset["Gender"].map(gender_mapping)
display(dataset)

Gender     Height      Weight
0          0  73.847017  241.893563
1          0  68.781904  162.310473
2          0  74.110105  212.740856
3          0  71.730978  220.042470
4          0  69.881796  206.349801
...      ...        ...         ...
9995       1  66.172652  136.777454
9996       1  67.067155  170.867906
9997       1  63.867992  128.475319
9998       1  69.034243  163.852461
9999       1  61.944246  113.649103

[10000 rows x 3 columns]

In [23]:
#put the columns of ones into the front of the dataset
### EXERCISE CODE HERE

In [38]:
X = ### EXERCISE CODE HERE
y = dataset["Weight"].values

In [39]:
X

array([[ 1.        ,  0.        , 73.84701702],
       [ 1.        ,  0.        , 68.78190405],
       [ 1.        ,  0.        , 74.11010539],
       ...,
       [ 1.        ,  1.        , 63.86799221],
       [ 1.        ,  1.        , 69.03424313],
       [ 1.        ,  1.        , 61.94424588]])

In [33]:
y

array([241.89356318, 162.31047252, 212.74085556, ..., 128.47531878,
       163.85246135, 113.64910268])

In [40]:
# Calculating the coefficients using the normal equation: (X^T * X)^(-1) * X^T * y
coefficients = ### EXERCISE CODE HERE
print(coefficients)

[-225.545792    -19.37771052    5.97694123]


predict the weight of someone with height of 70 and who have gender `male`

In [42]:
X_test = np.array([1,0,70])

# Making predictions for the test set
y_prediction = ### EXERCISE CODE HERE
print(y_prediction)

192.8400939530078
