# Python syntaxes

#### list indexing

In [2]:
letter_list = ['a','b','c','d','e','f','g']

print("first item:",letter_list[0])
print("last item:",letter_list[-1])

first item: a
last item: g


In [3]:
print("from item 0 till item 3 (excluding item 3):",letter_list[0:3])

print("from item 0 till item 3 (excluding item 3):",letter_list[ :3])


from item 0 till item 3 (excluding item 3): ['a', 'b', 'c']
from item 0 till item 3 (excluding item 3): ['a', 'b', 'c']


#### for each loops


In [4]:
number_list = [11,22,33,44,55]
for num in number_list:
	print(num)

11
22
33
44
55


#### for range

In [5]:
for num in range(10):
    print(num)

0
1
2
3
4
5
6
7
8
9


In [6]:
for num in range(10,20):
    print(num)

10
11
12
13
14
15
16
17
18
19


In [7]:
for num in range(10,20,2):
    print(num)

10
12
14
16
18


#### List comprehension

In [8]:
numbers = []
for garbage in range(10):
    numbers.append([])
print(numbers)

numbers = [ [] for f in range(10)]
numbers = [ [],]*10
print(numbers)

[[], [], [], [], [], [], [], [], [], []]
[[], [], [], [], [], [], [], [], [], []]


#### Enumerate 

In [9]:
list = ["a","b","c"]

for index in range(3):
    item = list[index]
    print(index, item)
    
for index, item in enumerate(list):
    print(index,item)

0 a
1 b
2 c
0 a
1 b
2 c


# numpy syntaxes

In [10]:
import numpy as np

#### `arange` 

In [11]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.random.randn(5)

array([-0.7498227 , -0.16431061,  1.42799019,  2.03514258, -0.11426025])

In [14]:
array1 = np.array([1,2,3,4,5])
array2 = np.array([10,20,30,40,50])

#### element wise product

In [15]:
array1*array2

array([ 10,  40,  90, 160, 250])

#### dot product

In [16]:
array1@array2

550

In [17]:
array1 = np.array([1,2,3,4,5])
array1**2

array([ 1,  4,  9, 16, 25])

In [23]:
array1 = np.array([1,2,3,4,5])
array1*2

array([ 2,  4,  6,  8, 10])

In [24]:
array1 = np.array([1,2,3,4,5])
array2 = np.array([10,20,30,40,50])
array1+array2

array([11, 22, 33, 44, 55])

In [26]:
arr = np.array([ [1,2],[3,4],[5,6]])
print(arr)
arr.shape

array([1, 2, 3, 4, 5])

In [41]:
arr1d = np.array([1,2,3,4,5])
arr1d.shape

(5,)

In [35]:
arr1d = np.array([1,2,3,4,5])
arr2d = arr1d.reshape(5,1)
arr2d.shape

(5, 1)

In [43]:
print(arr1d.T)
print(arr2d.T)

[1 2 3 4 5]
[[1 2 3 4 5]]


In [46]:
print("multipying 1d arrays:\n",arr1d.T * arr1d)
print("multipying 2d arrays:\n",arr2d.T * arr2d)

multipying 1d arrays:
 [ 1  4  9 16 25]
multipying 2d arrays:
 [[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]


In [18]:
arr = np.array([5.1, 2.0, 9.4, 7.8, 1.2, 6.2])
np.argmax(arr) #gives the index of the biggest item (9.4 is in index 2)

2

In [19]:
arr = np.array([5.1, 2.0, 9.4, 7.8, 1.2, 6.2])
np.argmin(arr) #gives the index of the smallest item (1.2 is in index 4)

4

#### np.unique removes all duplicates in an array

In [20]:
arr = np.array([1,1,2,3,4,4,4,4,4,4,4,4,4])
np.unique(arr)

array([1, 2, 3, 4])

#### np.unique(return_inverse=True) removes all duplicates in an array AND renames the unique items from 0 to N

In [21]:
arr = np.array([5,5,6,7,8,8,8,8,8,8])
np.unique(arr, return_inverse=True)

(array([5, 6, 7, 8]), array([0, 0, 1, 2, 3, 3, 3, 3, 3, 3]))

#### np.unique(return_inverse=True) removes all duplicates in an array AND renames the unique items from 0 to N

In [22]:
arr = np.array([1,1,2,3,4,4,4,4,4,4,4,4,4])
np.unique(arr, return_counts=True)

(array([1, 2, 3, 4]), array([2, 1, 1, 9]))

# Shell commands

In [53]:
# ! linux command
! uname -a

Linux 7065457a9ede 5.15.109+ #1 SMP Wed Jun 28 11:06:41 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux


In [58]:
! ls /

'=2.*'	      entrypoint.sh	    lib      mnt    run_jupyter.sh   tmp
'=2023.0.1'   etc		    lib32    opt    sbin	     usr
 bin	      home		    lib64    proc   src		     var
 boot	      install_packages.sh   libx32   root   srv
 dev	      kaggle		    media    run    sys


In [54]:
! pwd

/kaggle/working


In [55]:
! git

usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

These are common Git commands used in various situations:

start a working area (see also: git help tutorial)
   clone             Clone a repository into a new directory
   init              Create an empty Git repository or reinitialize an existing one

work on the current change (see also: git help everyday)
   add               Add file contents to the index
   mv                Move or rename a file, a directory, or a symlink
   restore           Restore working tree files
   rm                Remove files from the working tree and from the index
   sparse-checkout   Initialize and modify the sparse-checkout

examine the history and state (see also: git help revisio